INSERT INTO employees(id, first_name, last_name, title, department, salary, manager)
VALUES  (1, "SpongeBob", "Squarepants", "Sales Person", "Sales", 500000, "Eugene Krabs")
        (2, "Eugene", "Krabs", "Sales Lead", "Sales", 100000)
        (3, "Patrick", "Star", "Sales Person", "Sales", 300000, "Eugene Krabs")
        (4, "Squidward", "Tentacles", "Accountant", "Finance", 450000, "Eugene Krabs")
